# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kov < Formula
  desc "Indestructible AI coding in your terminal"
  homepage "https://trykov.dev"
  version "0.1.3"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/up1512001/kov/releases/download/v0.1.3/kov_0.1.3_darwin_amd64.tar.gz"
      sha256 "d62c917506a538b3a09001d8ac5571c2da7aa95a46dc599b9f418202b78bda99"

      define_method(:install) do
        bin.install "kov"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/up1512001/kov/releases/download/v0.1.3/kov_0.1.3_darwin_arm64.tar.gz"
      sha256 "695f6a45e678c0d62a4ea7d409f18afab605f8e7211d568f6bca83e446aa8d06"

      define_method(:install) do
        bin.install "kov"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/up1512001/kov/releases/download/v0.1.3/kov_0.1.3_linux_amd64.tar.gz"
      sha256 "f33d00a1dc5b653047d27ecf372f9055c14415a2b203b4b886d880aceee88e86"
      define_method(:install) do
        bin.install "kov"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/up1512001/kov/releases/download/v0.1.3/kov_0.1.3_linux_arm64.tar.gz"
      sha256 "d687fb140e89e037808c75a8ef5f8ead5139e6c43acf6d8a762eb970ca0fbeb2"
      define_method(:install) do
        bin.install "kov"
      end
    end
  end

  test do
    system "#{bin}/kov", "version"
  end
end
