# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Membox < Formula
  desc "Memory Box — git-like Mac backup powered by rsync"
  homepage "https://github.com/up1512001/memorybox"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/up1512001/memorybox/releases/download/v0.5.0/memorybox_0.5.0_darwin_amd64.tar.gz"
      sha256 "5cec9b400fc53198499245f67c1afec413b815a8f8f62c0d4b6d1281c93d4c1a"

      define_method(:install) do
        bin.install "membox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/up1512001/memorybox/releases/download/v0.5.0/memorybox_0.5.0_darwin_arm64.tar.gz"
      sha256 "292a3253297590cce5071992bba9cf560a1d211f4510360d1f90d894a876a1af"

      define_method(:install) do
        bin.install "membox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/up1512001/memorybox/releases/download/v0.5.0/memorybox_0.5.0_linux_amd64.tar.gz"
      sha256 "66c23ffb1ed41c7c6a8cd1a3366db7c59cf7dfa58724a8b2af52c3a74be2c1a5"
      define_method(:install) do
        bin.install "membox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/up1512001/memorybox/releases/download/v0.5.0/memorybox_0.5.0_linux_arm64.tar.gz"
      sha256 "5300714d5bb8ad337b99b80dfb49592bb9047affd24c5ca42c5d6d21b62987b2"
      define_method(:install) do
        bin.install "membox"
      end
    end
  end

  test do
    system "#{bin}/membox", "--version"
  end
end
