# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Membox < Formula
  desc "Memory Box — git-like Mac backup powered by rsync"
  homepage "https://github.com/up1512001/memorybox"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/up1512001/memorybox/releases/download/v0.4.0/memorybox_0.4.0_darwin_amd64.tar.gz"
      sha256 "abc3ff8feea7a9383a30ed48af2021dec513865c5b7d5eee646e0b9281a33692"

      define_method(:install) do
        bin.install "membox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/up1512001/memorybox/releases/download/v0.4.0/memorybox_0.4.0_darwin_arm64.tar.gz"
      sha256 "484da85441326e3f04ebe172de10e9a3fe8bb751555ad70f2e40e7f7442756c2"

      define_method(:install) do
        bin.install "membox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/up1512001/memorybox/releases/download/v0.4.0/memorybox_0.4.0_linux_amd64.tar.gz"
      sha256 "a3b7e5a893fc00ec6b88af8b7c90b48ee132c76dd4e939249b963e8ecfa5c9bb"
      define_method(:install) do
        bin.install "membox"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/up1512001/memorybox/releases/download/v0.4.0/memorybox_0.4.0_linux_arm64.tar.gz"
      sha256 "a5838a6619828fabed0bbaf19c7be1c29afb504022959623bb8ef0d17eb05697"
      define_method(:install) do
        bin.install "membox"
      end
    end
  end

  test do
    system "#{bin}/membox", "--version"
  end
end
